version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
     # You can also specify other tool versions:
     # nodejs: "18"
     # rust: "1.64"

python:
   install:
   - requirements: docs/requirements.txt
   
sphinx:
  configuration: docs/conf.py
